# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec97cf453cc90db2e7c1582306ce035e008c09ef1c6837a765a08571580a22794a56841ba01b36dafba4fa48c4172de81a380506d2ceccd1f082206ef0bb381

test:
  secret_key_base: a963e76b8d8308afcd2d1795cb932b9eb79d1f4a7d4bc3c483c0a99ff8341d9f27a8f84af11e26ae7c86e1511006a8749bc7d802f304dbb96b82224a2c229fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
